<?php

/**
 * Implements hook_theme().
 */
function illinois_framework_core_theme() {
  return array(
    'media_remote_illinois_mediaspace' => array(
      'variables' => array(
        'url' => NULL,
        'width' => NULL,
        'height' => NULL,
      ),
    ),
  );
}

function illinois_framework_core_preprocess_field(&$variables) {
  $variables['node'] = $variables['element']['#object'];
}
